platformName=Android
deviceName=emulator-5554
automationName=UiAutomator2
appPackage=com.saucelabs.mydemoapp.android
appActivity=com.saucelabs.mydemoapp.android.view.activities.SplashActivity
appPath=src/test/resources/apps/mda.apk
implicitWait=10
explicitWait=10
noReset=false
fullReset=false
